# Generated by Django 5.2 on 2025-04-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Donor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Age', models.PositiveIntegerField()),
                ('Blood_Type', models.CharField(max_length=3)),
                ('Date_Of_Birth', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=1024)),
                ('PinCode', models.CharField(max_length=8)),
                ('District', models.CharField(max_length=30, null=True)),
                ('Hospital', models.CharField(max_length=80, null=True)),
                ('State', models.CharField(max_length=15)),
                ('Weight', models.FloatField(max_length=6)),
                ('Diabetic', models.CharField(max_length=5)),
                ('HIV', models.CharField(max_length=5)),
                ('Medicine', models.CharField(max_length=5)),
                ('Medicine_Name', models.CharField(max_length=30, null=True)),
                ('Disease', models.CharField(max_length=5)),
                ('Disease_Name', models.CharField(max_length=30, null=True)),
                ('Surgery', models.CharField(max_length=5)),
                ('Surgery_Name', models.CharField(max_length=30, null=True)),
                ('Donated_Previous', models.CharField(max_length=5)),
                ('Donated_Date', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('E_mail', models.CharField(max_length=50)),
                ('PH_number', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='blood_request_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_users')),
            ],
            options={
                'unique_together': {('hospital', 'patient_name')},
            },
        ),
    ]
