# Generated by Django 5.2 on 2025-04-17 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_bloodrequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
