# Generated by Django 5.2 on 2025-04-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
