# Generated by Django 5.2 on 2025-04-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
