# Generated by Django 5.2 on 2025-04-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donor_register',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.blood_users'),
        ),
    ]
