# Generated by Django 5.2 on 2025-04-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_blood_donor_register_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_donor_register',
            name='registered_by',
        ),
    ]
