# Generated by Django 5.2 on 2025-04-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_blood_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_users',
            name='user',
        ),
    ]
