# Generated by Django 4.1.1 on 2022-11-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organ_users',
            old_name='UserName',
            new_name='Username',
        ),
    ]
