# Generated by Django 4.1.1 on 2022-12-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0003_alter_organ_users_e_mail_alter_organ_users_ph_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ_Donor_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Father_Name', models.CharField(max_length=30)),
                ('Mother_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=1024)),
                ('City', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('PinCode', models.CharField(max_length=8)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('E_mail', models.CharField(max_length=50)),
                ('PH_number', models.CharField(max_length=15)),
                ('Occupation', models.CharField(max_length=20)),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Id_Card', models.FileField(upload_to='documents/')),
                ('Emergency_Contact_Name', models.CharField(max_length=30)),
                ('Emergency_Contact_Phone', models.CharField(max_length=15)),
                ('Emergency_Contact_Address', models.CharField(max_length=30)),
                ('Organ', models.CharField(max_length=10)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.organ_users')),
            ],
        ),
    ]
