# Generated by Django 4.1.1 on 2022-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0004_organ_donor_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donor_form',
            name='Id_Card',
            field=models.FileField(upload_to='media/'),
        ),
    ]
