# Generated by Django 4.1.1 on 2022-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0006_alter_organ_donor_form_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donor_form',
            name='Id_Card',
            field=models.FileField(upload_to='files/'),
        ),
    ]
