# Generated by Django 5.2 on 2025-04-18 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0009_organ_types_organ_users_remove_organmatch_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ_donor_register',
            name='kidney_donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_donor_register',
            name='liver_donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_donor_register',
            name='medical_evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_donor_register',
            name='psychological_evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_donor_register',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organ_donor_register',
            name='understood_risks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_types',
            name='Living_Donation_Eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ_types',
            name='Viability_Hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='organinventory',
            name='is_kidney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organinventory',
            name='is_liver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organinventory',
            name='kidney_side',
            field=models.CharField(blank=True, choices=[('left', 'Left Kidney'), ('right', 'Right Kidney')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organinventory',
            name='liver_portion',
            field=models.CharField(blank=True, choices=[('left_lobe', 'Left Lobe'), ('right_lobe', 'Right Lobe'), ('segment', 'Segment'), ('whole', 'Whole Liver')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organinventory',
            name='organ_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='is_kidney_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='is_liver_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='specific_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganDonorSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kidney', models.BooleanField(default=False)),
                ('kidney_function_test_completed', models.BooleanField(default=False)),
                ('kidney_side', models.CharField(choices=[('left', 'Left Kidney'), ('right', 'Right Kidney'), ('either', 'Either Kidney')], default='either', max_length=10)),
                ('is_liver', models.BooleanField(default=False)),
                ('liver_function_test_completed', models.BooleanField(default=False)),
                ('liver_portion', models.CharField(choices=[('left_lobe', 'Left Lobe'), ('right_lobe', 'Right Lobe'), ('segment', 'Segment'), ('any', 'Any Portion')], default='any', max_length=20)),
                ('additional_tests_completed', models.BooleanField(default=False)),
                ('specialist_consultation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_selections', to='organ.organ_donor_register')),
                ('organ_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.organ_types')),
            ],
            options={
                'verbose_name': 'Organ Donor Selection',
                'verbose_name_plural': 'Organ Donor Selections',
                'unique_together': {('donor', 'organ_type')},
            },
        ),
    ]
